name: Create Image and Save Link

on:
  push:
    branches:
      - main 

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python main.py

      - name: Commit and push if changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated update"
          git push
